name: Build

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * 0"
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          ./installResources.ps1

      - name: executable
        run: |
          pyinstaller --onefile --noconsole project.py

      - name: upload
        uses: actions/upload-artifact@v2
        with:
          name: executable
          path: dist/project.exe
